/**
 * random_prompt_pool.ts — AIBO ランダムプロンプトモード用 語彙プール
 *
 * 設計: 固定スケルトン + 6カテゴリから各1語をランダム抽出して合成(combinatorial)。
 *   約 144 / 135 / 38 / 38 / 35 / 40 ≈ 430 語 → 組み合わせ ≈ 約390億通り。
 * 方針: 正面・カメラ目線・photoreal は固定(PuLID identity が最も安定する条件)。
 *   identity 抑制ワード("mannequin-style" / "no smile" 等)は意図的に不採用。
 *   上品でブランドトーンに合うカジュアル/ライフスタイル/ルックブック寄りで統一。
 * 拡張: 各配列に行を足すだけ。重複・破綻ワードは入れない。
 */

export const SKELETON =
  "front-facing portrait photo, looking directly at camera, photorealistic, sharp focus on face";

export const POOLS = {
  // 衣装(コーディネート1フレーズ・上品カジュアル中心)
  outfit: [
    "a white ribbed knit top",
    "an oversized beige cardigan",
    "a black turtleneck sweater",
    "a denim jacket over a white tee",
    "a cream wool coat",
    "a soft pastel hoodie",
    "a silk camisole with a light shawl",
    "a tailored blazer over a tee",
    "a chunky cable-knit sweater",
    "a rolled-sleeve linen shirt",
    "an off-white trench coat",
    "a plaid flannel shirt",
    "a fitted gray henley",
    "a pale pink cardigan",
    "a navy peacoat",
    "a cropped denim jacket",
    "a crisp white button-down",
    "a ribbed tank with a light cardigan",
    "a mustard knit vest over a blouse",
    "a sage green sweater",
    "a corduroy overshirt",
    "a sleeveless turtleneck",
    "a quilted puffer jacket",
    "a pastel blue sweatshirt",
    "a classic white tee",
    "a knit polo shirt",
    "a camel turtleneck",
    "a breton-striped long-sleeve",
    "a terracotta knit top",
    "an ivory cashmere sweater",
    "an olive utility jacket",
    "a soft gray crewneck",
    "a pinstripe shirt",
    "a pale yellow cardigan",
    "a fitted black blazer",
    "an oatmeal turtleneck dress",
    "a light chambray shirt",
    "a burgundy knit sweater",
    "a white linen blouse",
    "a dusty-rose cardigan",
    "a charcoal hoodie",
    "a minimal beige tank top",
    "a soft lavender blouse",
    "a checkered wool overcoat",
    "a relaxed white sweatshirt",
    "a knit cardigan over a collared shirt",
    "a pale green linen dress",
    "a cozy oversized turtleneck",
    "a soft turtleneck under a pinafore dress",
    "a cropped wool sweater",
    "a relaxed oversized shirt",
    "a soft argyle knit vest",
    "a pale grey turtleneck",
    "a soft mohair cardigan",
    "a structured camel coat",
    "a belted wrap coat",
    "a double-breasted overcoat",
    "a shearling-collar jacket",
    "a soft fleece pullover",
    "a striped knit sweater",
    "a v-neck cashmere sweater",
    "a boat-neck striped top",
    "a mock-neck ribbed top",
    "a draped silk blouse",
    "a high-neck lace blouse",
    "a puff-sleeve blouse",
    "a tie-neck blouse",
    "a peter-pan-collar blouse",
    "a soft button-up shirt dress",
    "a sleeveless shift dress",
    "a knit sweater dress",
    "a corduroy pinafore dress",
    "a flowy midi dress",
    "a wrap dress with a soft print",
    "a tiered cotton dress",
    "a smocked summer dress",
    "a linen sundress",
    "a pleated-collar dress",
    "a soft cardigan over a slip dress",
    "a denim shirt tucked in",
    "a soft seersucker shirt",
    "a flannel-lined overshirt",
    "a quilted vest over a knit",
    "a puffer gilet over a turtleneck",
    "a longline cardigan",
    "a chunky turtleneck with a scarf",
    "a fair-isle knit sweater",
    "a cable-knit cardigan",
    "a waffle-knit henley",
    "a soft hoodie under a denim jacket",
    "a varsity-style jacket",
    "a bomber jacket over a tee",
    "a leather biker jacket",
    "a soft suede jacket",
    "a tweed blazer",
    "a houndstooth coat",
    "a checked overshirt",
    "a soft pastel knit set",
    "a ribbed loungewear set",
    "a relaxed linen co-ord",
    "a cropped cardigan with high-waist trousers",
    "a turtleneck under dungarees",
    "a soft knit with a pleated skirt",
    "a blouse with wide-leg trousers",
    "a tucked tee with tailored pants",
    "a fitted top with paperbag trousers",
    "a soft sweater with a midi skirt",
    "a cardigan with a slip skirt",
    "a shirt with rolled cuffs and chinos",
    "a turtleneck with corduroy trousers",
    "a knit vest over a white shirt",
    "a sleeveless blouse with culottes",
    "a soft tee under overalls",
    "a cropped sweatshirt",
    "a relaxed raglan tee",
    "a striped breton dress",
    "a soft jersey top",
    "a ribbed bodysuit under a blazer",
    "a halter-neck knit top",
    "a square-neck blouse",
    "a sweetheart-neck top",
    "a cowl-neck sweater",
    "a turtleneck mini dress",
    "a soft angora sweater",
    "a pastel pink coat",
    "a sky-blue cardigan",
    "a soft mint sweater",
    "a butter-yellow blouse",
    "a warm rust-colored knit",
    "a deep teal sweater",
    "a soft coral cardigan",
    "a powder-blue turtleneck",
    "a sand-colored trench",
    "a soft taupe coat",
    "a chocolate-brown sweater",
    "a forest-green knit",
    "a cream turtleneck dress",
    "a soft ecru cardigan",
    "a pale denim jacket",
    "a washed-blue chambray dress",
    "a cozy cardigan with a tee",
    "a relaxed knit polo dress",
    "a soft cropped puffer",
    "a tailored vest over a blouse",
  ],

  // ロケーション / 背景
  scene: [
    "in a sunlit corner cafe",
    "on an urban rooftop at dusk",
    "in a minimalist white studio",
    "in an autumn park with fallen leaves",
    "on a seaside boardwalk",
    "in a cozy independent bookshop",
    "on a city street at golden hour",
    "in a sunroom full of plants",
    "in a quiet art gallery",
    "by a rainy window indoors",
    "on a spring cherry-blossom path",
    "on a neon-lit night street",
    "in a vintage record store",
    "in a modern apartment by the window",
    "by a foggy morning riverside",
    "among flower-market stalls",
    "on a subway platform",
    "in an old stone alley",
    "on a beach at sunset",
    "on a snowy winter street",
    "in a greenhouse conservatory",
    "in a rooftop garden",
    "in a minimalist concrete loft",
    "at a warm-lit ramen bar",
    "in a university campus courtyard",
    "on a coastal cliff overlook",
    "against a pastel pink wall",
    "on a forest trail in soft light",
    "on a terrace overlooking the city",
    "on a cobblestone European lane",
    "in a midcentury living room",
    "by a train window seat",
    "in a lavender field",
    "in an industrial brick studio",
    "at a harbor during blue hour",
    "on quiet temple grounds",
    "in a sunflower field",
    "on a rooftop pool deck",
    "at a candle-lit cafe interior",
    "in a softly lit home kitchen",
    "under a wisteria-covered pergola",
    "in a sunlit reading nook",
    "on a quiet riverside bench",
    "in a pastel-toned hallway",
    "at a flower-filled balcony",
    "in a bustling morning market",
    "at a quiet train station",
    "on a highway overpass at dusk",
    "in a sunlit botanical garden",
    "at a poolside in summer",
    "on a wooden pier at dawn",
    "in a mountain cabin interior",
    "by a crackling fireplace",
    "in a vintage diner booth",
    "at a rooftop bar at night",
    "on a balcony overlooking the sea",
    "in a cozy attic studio",
    "at a farmers' market",
    "in a tea house with paper screens",
    "in a Kyoto-style garden",
    "along a canal in the old town",
    "on a Parisian cafe terrace",
    "in a minimalist Japanese apartment",
    "in a tatami-floored room",
    "in a sunlit ceramics studio",
    "in a quiet university library",
    "at a vinyl listening bar",
    "in a soft pink bedroom",
    "on a city fire-escape",
    "in a glass-walled atrium",
    "on a misty forest path",
    "in a bamboo grove",
    "by a koi pond in a garden",
    "on a hilltop at sunset",
    "in a field of tall grass",
    "on a country road at golden hour",
    "in a vineyard at harvest time",
    "on a stone bridge over a stream",
    "in a snowy pine forest",
    "at an ice-skating rink",
    "in a warm-lit izakaya",
    "at a street-food stall at night",
    "on a Tokyo backstreet",
    "under cherry blossoms at night",
    "in a softly lit jazz bar",
    "in a quiet hotel lobby",
    "on a marble staircase",
    "in a sunlit corridor with arches",
    "in a courtyard with a fountain",
    "on a rooftop helipad",
    "in a glass greenhouse cafe",
    "at a seaside cafe with white walls",
    "on a sandy dune at sunset",
    "in a tide-pool cove",
    "at a lighthouse on the coast",
    "in a misty tea plantation",
    "on a boardwalk through the reeds",
    "in an autumn maple forest",
    "under a canopy of ginkgo leaves",
    "in a quiet morning meadow",
    "at a window booth on a train",
    "in a retro arcade",
    "at a neon-lit convenience store",
    "on a rain-slicked night crossing",
    "under glowing paper lanterns",
    "at a summer festival at dusk",
    "in a softly lit photo studio",
    "against a seamless gray backdrop",
    "against a warm beige backdrop",
    "against a deep navy backdrop",
    "in a loft with floor-to-ceiling windows",
    "in a sunroom at golden hour",
    "in a plant-filled cafe corner",
    "at a marble-topped kitchen island",
    "on a velvet sofa indoors",
    "in a reading chair by a lamp",
    "at a desk by a bright window",
    "in a softly lit hallway",
    "on a spiral staircase",
    "in a converted warehouse space",
    "on a rooftop at blue hour",
    "on a city bridge at dusk",
    "in a quiet alley with climbing vines",
    "at a flower shop entrance",
    "in a pastel macaron cafe",
    "at a bakery window",
    "in a softly lit wine bar",
    "on a terrace among potted plants",
    "in a sunlit corner with sheer curtains",
    "by a large arched window",
    "in a minimalist gallery hallway",
    "on a quiet beach at dawn",
    "in a snow-dusted courtyard",
    "at a hillside overlooking the city lights",
    "in a warm-toned living room at evening",
  ],

  // ライティング
  lighting: [
    "soft natural daylight",
    "warm golden-hour glow",
    "gentle window backlight",
    "overcast diffused light",
    "bright airy daylight",
    "moody studio rim light",
    "soft pink sunset light",
    "cool blue-hour tones",
    "warm indoor lamp glow",
    "dappled light through leaves",
    "crisp morning light",
    "neon ambient glow",
    "candle-lit warmth",
    "high-key bright lighting",
    "low-key dramatic shadows",
    "a soft backlit hair glow",
    "soft overcast portrait light",
    "golden backlight haze",
    "cinematic side lighting",
    "diffused softbox light",
    "warm tungsten interior light",
    "cold clear winter daylight",
    "sun flare through a window",
    "twilight ambient light",
    "silvery overcast tone",
    "soft reflected fill light",
    "amber evening light",
    "pale blue dawn light",
    "softened midday sun",
    "glowing string-light bokeh",
    "cool moonlit tones",
    "warm cafe lamp light",
    "gentle rainy-day light",
    "a spotlit studio key light",
    "hazy summer-afternoon light",
    "foggy diffused glow",
    "warm firelight",
    "bright beachside sunlight",
  ],

  // 表情 / ムード
  mood: [
    "a gentle natural smile",
    "a candid soft laugh",
    "a calm thoughtful gaze",
    "a playful glance",
    "a serene relaxed expression",
    "a warm friendly smile",
    "a quiet contemplative look",
    "a soft confident expression",
    "a dreamy faraway gaze",
    "a bright cheerful smile",
    "a subtle knowing smile",
    "a peaceful soft expression",
    "a curious tilted-head look",
    "a tender gentle expression",
    "a relaxed candid mood",
    "a soft surprised look",
    "a gentle laughing moment",
    "a composed elegant gaze",
    "a wistful soft expression",
    "a sunny carefree smile",
    "a soft introspective mood",
    "a kind warm expression",
    "a lively bright look",
    "a calm steady gaze",
    "a delicate shy smile",
    "a content peaceful look",
    "a soft daydreaming gaze",
    "a graceful relaxed expression",
    "a quiet confident look",
    "a playful mid-laugh moment",
    "a tender wistful smile",
    "a fresh morning calm",
    "a soft glowing happiness",
    "a gentle inviting smile",
    "a relaxed natural ease",
    "a serene poised expression",
    "a warm candid joy",
    "a thoughtful side glance",
  ],

  // 写真 / 美学スタイル
  style: [
    "soft film photography",
    "clean editorial portrait",
    "candid lifestyle shot",
    "natural lookbook style",
    "cinematic color grading",
    "fashion-magazine aesthetic",
    "warm analog film look",
    "minimalist Scandinavian style",
    "dreamy soft-focus aesthetic",
    "documentary candid style",
    "polished beauty shot",
    "vintage 90s film tone",
    "modern Korean portrait style",
    "soft pastel palette",
    "moody cinematic tone",
    "bright airy aesthetic",
    "street-style photography",
    "cozy autumn aesthetic",
    "crisp high-end commercial look",
    "coffee-table-book style",
    "gentle pastel film",
    "refined natural-beauty style",
    "contemporary editorial look",
    "warm nostalgic tone",
    "clean studio portrait",
    "soft romantic aesthetic",
    "effortless off-duty style",
    "muted earthy palette",
    "glossy fashion editorial",
    "natural unretouched look",
    "soft pastel dream aesthetic",
    "understated elegant style",
    "breezy summer aesthetic",
    "subtle film-grain texture",
    "warm golden aesthetic",
  ],

  // ディテール / 仕上げ
  accent: [
    "soft bokeh background",
    "windswept loose hair",
    "delicate gold earrings",
    "dewy natural skin",
    "a few loose strands of hair",
    "shallow depth of field",
    "subtle warm color tones",
    "a thin silver necklace",
    "soft background blur",
    "naturally flushed cheeks",
    "gentle catchlights in the eyes",
    "a light silk scarf",
    "tousled effortless hair",
    "soft pastel color tones",
    "a delicate hair clip",
    "glowing healthy skin",
    "a faint dusting of freckles",
    "creamy background blur",
    "a neat low ponytail",
    "soft side-swept bangs",
    "a light touch of blush",
    "a cozy knit scarf",
    "subtle film grain",
    "airy floating hair",
    "minimal natural makeup",
    "a pair of round glasses",
    "soft morning haze",
    "a gentle lens flare",
    "a braided hair detail",
    "warm rim light on the hair",
    "delicate stud earrings",
    "soft matte skin texture",
    "loose beachy waves",
    "a thin layered necklace",
    "subtle golden highlights",
    "a fresh dewy complexion",
    "a slim leather watch",
    "wisps of hair catching the light",
    "a soft cashmere texture",
    "a clean centre hair part",
  ],
} as const;

export type PoolKey = keyof typeof POOLS;

const ORDER: PoolKey[] = ["outfit", "scene", "lighting", "mood", "style", "accent"];

/** [0,1) を返す乱数を受け取り、1スロット1語で合成したランダムプロンプトを返す */
export function rollRandomPrompt(rng: () => number = Math.random): string {
  const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(rng() * arr.length)];
  return [SKELETON, ...ORDER.map((k) => pick(POOLS[k]))].join(", ");
}

/** 組み合わせ総数(参考) */
export const TOTAL_COMBINATIONS = ORDER.reduce((n, k) => n * POOLS[k].length, 1);
